### ISSUE TITLE
Add Announcement Notifications

### ISSUE THREAD

**Issue by kevinhinterlong** [HackIllinois/android-2017#65]
I'm not sure what the expected behavior is for notifications 
- We'll probably fetch Announcements every 30 min.
- On first fetch
   - just fetch all notifications after current time
- Subsequent fetch
   - after=last fetch
   - save current time as last fetch

Some things to consider are:
- Announcements have a `title` but currently this isn't being used in the design, should it be?

- If the user is already in the app should we show a toast? Or just make the notifications anyways?

**Comment by dl-eric** [comment]
We decided to not have announcements get pushed?

**Comment by kevinhinterlong** [comment]
Yep, as of now we're still manually fetching them
