### ISSUE TITLE
Announcments Background should be white

### ISSUE THREAD

**Issue by kevinhinterlong** [HackIllinois/android-2017#95]
The announcement items should look more like the events, where each item is on a card

<img src="https://raw.githubusercontent.com/HackIllinois/android-2017/v1.1.3/app/src/main/play/en-US/listing/phoneScreenshots/3.png" width="170"/> <img src="https://raw.githubusercontent.com/HackIllinois/android-2017/v1.1.3/app/src/main/play/en-US/listing/phoneScreenshots/1.png" width="170"/>

**Comment by Avasse** [comment]
Hello, i'd be glad to work on this issue to conclude my first PR, is anyone working on it ?
